server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: 'classpath:dml.sql'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#    hibernate:
#      ddl-auto: create-drop