server:
  port: 8080
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
  sql:
    init:
      data-locations: 'classpath:dml.sql'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true