INSERT INTO member (member_id, email, nickname, password, role, status, created_at, updated_at) VALUES
(RANDOM_UUID(), 'admin1@naver.com', 'admin1', '$2a$10$18N4y7HsEr.uKsi5EX44Ae5w5RG4WCc1DNjmtu.uuG10pHm1RXbWi', 0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(RANDOM_UUID(), 'admin2@naver.com', 'admin2', '$2a$10$18N4y7HsEr.uKsi5EX44Ae5w5RG4WCc1DNjmtu.uuG10pHm1RXbWi', 0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(RANDOM_UUID(), 'basic@naver.com', 'basic', '$2a$10$18N4y7HsEr.uKsi5EX44Ae5w5RG4WCc1DNjmtu.uuG10pHm1RXbWi', 1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
-- qwer1234!!

INSERT INTO address (member_id, city, district, province, created_at, updated_at) VALUES
((SELECT member_id FROM member WHERE email = 'basic@naver.com'), 'seoul', 'seoul', 'seoul', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'basic@naver.com'), 'busan', 'busan', 'busan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO brand (member_id, name, license_number, phone_number, created_at, updated_at) VALUES
((SELECT member_id FROM member WHERE email = 'admin1@naver.com'), 'NIKE', 1234567890, 9876543210, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin2@naver.com'), 'GUCCI', 2345678901, 8765432119, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin1@naver.com'), 'ADIDAS', 2345678902, 8765432129, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin2@naver.com'), 'CHANEL', 2345678903, 8765432139, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin2@naver.com'), 'ZARA', 2345678904, 8765432149, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin2@naver.com'), 'DIOR', 2345678905, 8765432159, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin1@naver.com'), 'REEBOK', 2345678906, 8765432169, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin1@naver.com'), 'PUMA', 2345678907, 8765432179, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT member_id FROM member WHERE email = 'admin2@naver.com'), 'PRADA', 2345678908, 8765432189, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO product (brand_id, category, name, price, quantity, created_at, updated_at) VALUES
-- NIKE
((SELECT id FROM brand WHERE name = 'NIKE'), 0, 'TOP', 11200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 1, 'OUTER', 5500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 2, 'PANTS', 4200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 3, 'SNEAKERS', 9000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 4, 'BAG', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 5, 'HAT', 1700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 6, 'SOCKS', 1800, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'NIKE'), 7, 'ACCESSORY', 2300, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- CUCCI
((SELECT id FROM brand WHERE name = 'GUCCI'), 0, 'TOP', 10500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 1, 'OUTER', 5900, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 2, 'PANTS', 3800, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 3, 'SNEAKERS', 9100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 4, 'BAG', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 5, 'HAT', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 6, 'SOCKS', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'GUCCI'), 7, 'ACCESSORY', 2200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ADIDAS
((SELECT id FROM brand WHERE name = 'ADIDAS'), 0, 'TOP', 10000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 1, 'OUTER', 6200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 2, 'PANTS', 3300, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 3, 'SNEAKERS', 9200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 4, 'BAG', 2200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 5, 'HAT', 1900, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 6, 'SOCKS', 2200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ADIDAS'), 7, 'ACCESSORY', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- CHANEL
((SELECT id FROM brand WHERE name = 'CHANEL'), 0, 'TOP', 10100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 1, 'OUTER', 5100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 2, 'PANTS', 3000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 3, 'SNEAKERS', 9500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 4, 'BAG', 2500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 5, 'HAT', 1500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 6, 'SOCKS', 2400, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'CHANEL'), 7, 'ACCESSORY', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- ZARA
((SELECT id FROM brand WHERE name = 'ZARA'), 0, 'TOP', 10700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 1, 'OUTER', 5000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 2, 'PANTS', 3800, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 3, 'SNEAKERS', 9900, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 4, 'BAG', 2300, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 5, 'HAT', 1800, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 6, 'SOCKS', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'ZARA'), 7, 'ACCESSORY', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- DIOR
((SELECT id FROM brand WHERE name = 'DIOR'), 0, 'TOP', 11200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 1, 'OUTER', 7200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 2, 'PANTS', 4000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 3, 'SNEAKERS', 9300, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 4, 'BAG', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 5, 'HAT', 1600, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 6, 'SOCKS', 2300, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'DIOR'), 7, 'ACCESSORY', 1900, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- REEBOK
((SELECT id FROM brand WHERE name = 'REEBOK'), 0, 'TOP', 10500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 1, 'OUTER', 5800, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 2, 'PANTS', 3900, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 3, 'SNEAKERS', 9000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 4, 'BAG', 2200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 5, 'HAT', 1700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 6, 'SOCKS', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'REEBOK'), 7, 'ACCESSORY', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- PUMA
((SELECT id FROM brand WHERE name = 'PUMA'), 0, 'TOP', 10800, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 1, 'OUTER', 6300, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 2, 'PANTS', 3100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 3, 'SNEAKERS', 9700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 4, 'BAG', 2100, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 5, 'HAT', 1600, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 6, 'SOCKS', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PUMA'), 7, 'ACCESSORY', 2000, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- PRADA
((SELECT id FROM brand WHERE name = 'PRADA'), 0, 'TOP', 11400, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 1, 'OUTER', 6700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 2, 'PANTS', 3200, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 3, 'SNEAKERS', 9500, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 4, 'BAG', 2400, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 5, 'HAT', 1700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 6, 'SOCKS', 1700, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM brand WHERE name = 'PRADA'), 7, 'ACCESSORY', 2400, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
