server:
  port: 8081
spring:
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:tcp://localhost/~/database
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true